name: Deploy to Github Pages

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        
    steps:
      - uses: actions/checkout@v2
      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run i-all
      - run: cd playground && npm install vizpro
      # - run: git config --global user.email "vimuthmendis@gmail.com"
      # - run: git config --global user.name "VimuthM"
      - run: npm run deploy